[test]

diff --git a/.github/workflows/chocolatine.yaml b/.github/workflows/chocolatine.yaml
--- a/.github/workflows/chocolatine.yaml
+++ b/.github/workflows/chocolatine.yaml
@@ -21,21 +21,19 @@ jobs:
     steps:
       - uses: actions/checkout@v4
       - id: check_coding_style
-        run: |
-          check.sh $(pwd) $(pwd)
-          CODING_STYLE_ERRORS=$(cat $(pwd)/coding-style-reports.log)
-          for ERRORS in $CODING_STYLE_ERRORS; 
-            do
-              array=(`echo $ERRORS | sed 's/:/\n/g'`)
-              echo "::error file=${array[1]#./},title=${array[3]#./} coding style errors detected: ${array[2]#./}::${array[4]#./}"
-          done
-          if [[ -n $CODING_STYLE_ERRORS ]]
-          then
-            echo $CODING_STYLE_ERRORS
-            exit 1
-          else
-            echo No coding style errors detected
-          fi
+      run: |
+        check.sh $(pwd) $(pwd)
+        while IFS= read -r ERRORS
+        do
+          array=(`echo $ERRORS | sed 's/:/\n/g'`)
+          echo "::error file=${array[1]#./},line=${array[2]#./},col=0::${array[3]#./}"
+        done < "$(pwd)/coding-style-reports.log"
+        if [[ -s $(pwd)/coding-style-reports.log ]]
+        then
+          exit 1
+        else
+          echo No coding style errors detected
+        fi
   
 
   check_repo:
